Fix: fixed functionality for oca branding on missing creds in proof
openwallet-foundation/bifold-wallet pull request #1178
Opened 2024-06-24 22:06 UTC by wadeking98

# Summary of Changes

- Fixed the way we resolve oca on proof requests when credentials are missing in the wallet.
- Merged the get help text functionality to leverage the patched oca functionality
- Updates to some of the tests and default oca bundles to add get credential support urls

TODO: still need to update the showcase so it has a schema id or credDef Id restriction that can be used to look up the OCA bundle.

<img width="405" alt="image" src="https://github.com/openwallet-foundation/bifold-wallet/assets/36937407/5b3e3e17-86d9-4fbf-a2c2-43c6aa281c36">

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-06-24 22:11 UTC, bryce-mcmath requested changes
Issue with the Person credential help action no longer working (unless I'm mistaken)

2024-06-24 22:11 UTC, bryce-mcmath commented on packages/legacy/core/App/components/misc/CredentialCard11.tsx
> +          setHelpAction(() => () => {
How does this functionality work for credential help actions that don't open an external URL but rather navigate within the app? I'm thinking of the existing person credential help action for example.

2024-06-25 18:21 UTC, wadeking98 commented on packages/legacy/core/App/components/misc/CredentialCard11.tsx
> +          setHelpAction(() => () => {
I added credHelpAction overrides to fix this. The default action is to navigate to a url specified by OCA but we have the ability to override that in the container resolver

2024-06-25 19:12 UTC, bryce-mcmath approved these changes

2024-06-25 20:09 UTC, merged