feat: new proof request loading screen
openwallet-foundation/bifold-wallet pull request #1243
Opened 2024-08-22 18:23 UTC by jleach

# Summary of Changes

TBD

# Related Issues

n/a

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-10-01 20:58 UTC, bryce-mcmath approved these changes

2024-10-01 20:58 UTC, bryce-mcmath commented on packages/legacy/app/ios/ariesbifold.xcodeproj/project.pbxproj
Should we not commit this file?

2024-10-01 20:58 UTC, bryce-mcmath commented on packages/legacy/core/App/hooks/notifications.ts
> +// import { log } from 'console'
should probably remove

2024-10-01 20:58 UTC, bryce-mcmath commented on packages/legacy/core/App/components/animated/RecordLoading.tsx
> +              borderRadius: 5,
These width / margin numbers seem somewhat arbitrary, could they be explained or named?

2024-10-01 20:58 UTC, bryce-mcmath commented on packages/legacy/core/App/components/animated/RecordLoading.tsx
> +            <View style={[myStyle.rectangle, { width: 210, height: 25 }]} />
Same here

2024-10-01 20:58 UTC, bryce-mcmath requested changes
Sorry, meant to request changes but accidentally approved

2024-10-02 00:13 UTC, bryce-mcmath submitted a review, later dismissed

2024-10-02 00:14 UTC, bryce-mcmath commented
The xcode file is still included but that isn't a big deal it's just an EOF

2024-10-02 00:16 UTC, jleach commented
> The xcode file is still included but that isn't a big deal it's just an EOF

Fixed.

2024-10-02 00:16 UTC, bryce-mcmath approved these changes

2024-10-03 16:36 UTC, merged