chore: rename HeaderButton into ButtonWithIcon
openwallet-foundation/bifold-wallet pull request #1273
Opened 2024-10-03 22:19 UTC by tom11-nguyen

# Summary of Changes

This change renames the HeaderButton component in core/App/components to name: ButtonWithIcon, including file names and usages.

# Related Issues

https://github.com/openwallet-foundation/bifold-wallet/pull/1093

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-10-04 17:01 UTC, bryce-mcmath requested changes
This is a bit nitpicky but could we name it `IconButton`? Just because our standard button can also come with an icon alongside its text (for example, a loading spinner), but this component is specifically only an icon.

2024-10-04 23:45 UTC, jleach submitted a review, later dismissed

2024-10-04 23:47 UTC, jleach commented
If you want to specify the ticket number and it's not in this repo you need to use the format bcgov/bc-wallet-mobile#1093

2024-10-10 16:07 UTC, bryce-mcmath approved these changes
Looks good

2024-10-10 17:06 UTC, merged