fix: fixed non serializable values warning
openwallet-foundation/bifold-wallet pull request #1299
Opened 2024-10-24 23:46 UTC by al-rosenthal

refacoted component to expect id instead of a full credential

# Summary of Changes

- refactored `CredentialDetails.tsx` to expect `credentialId` instead of a credential object

# Related Issues

(BC Wallet 2225)[https://github.com/bcgov/bc-wallet-mobile/issues/2225]

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-10-28 20:03 UTC, bryce-mcmath commented
Is `credential` still being passed as a param to this screen from `NotificationListItem.tsx` and `chat-messages.tsx`?

2024-10-28 20:44 UTC, bryce-mcmath requested changes
Just officially requesting changes as per my comment above

2024-10-28 22:58 UTC, al-rosenthal commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +    // FIXME: change params to accept credential id to avoid 'non-serializable' warnings
I had a conversation with @bryce-mcmath and decided to not fix this as this feature is still being worked on

2024-10-29 16:28 UTC, MosCD3 approved these changes

2024-10-29 18:48 UTC, bryce-mcmath approved these changes
Great change! 👷🛠️

2024-10-29 18:48 UTC, merged