fix: small fixes
openwallet-foundation/bifold-wallet pull request #1304
Opened 2024-11-05 16:02 UTC by al-rosenthal

# Summary of Changes

- Cleaned up old `App.tsx`
- added additional exports to index
- cleaned up padding

# Related Issues

[BC-Wallet 2250](https://github.com/bcgov/bc-wallet-mobile/issues/2250)

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-11-05 19:57 UTC, bryce-mcmath requested changes
Just one thing, otherwise looks good

2024-11-05 19:57 UTC, bryce-mcmath commented on packages/legacy/app/App.tsx
I think @cvarjao recently mentioned we should keep the two `App.tsx` for now as one will eventually be an export that can be used as the default wrapper in the various Bifold projects. So this `App.tsx` will import the wrapper from core and just be an example of how to use it. Long story short, I think we keep them both for now.

2024-11-06 17:49 UTC, al-rosenthal commented on packages/legacy/app/App.tsx
restored from main

2024-11-06 23:22 UTC, bryce-mcmath approved these changes

2024-11-06 23:22 UTC, merged