feat: move the pin rules below the pin input
openwallet-foundation/bifold-wallet pull request #1316
Opened 2024-11-14 01:29 UTC by FarjadGov14

# Summary of Changes

- move the pin rules below the pin input

# Related Issues

Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2024-11-14 14:14 UTC, MosCD3 requested changes
Can you attach another screenshot showing inline error configured below?

2024-11-14 17:49 UTC, FarjadGov14 commented
> Can you attach another screenshot showing inline error configured below?

Attached.

2024-11-14 18:25 UTC, jleach commented
@FarjadGov14 Would you be able to change "enought" to "enough" in the screen shot text. Just has an extra `t` in it.

2024-11-14 20:02 UTC, FarjadGov14 commented
> @FarjadGov14 Would you be able to change "enought" to "enough" in the screen shot text. Just has an extra `t` in it.

@jleach @MosCD3 Done.

2024-11-14 20:45 UTC, MosCD3 approved these changes, later dismissed

2024-11-14 21:00 UTC, bryce-mcmath requested changes

2024-11-14 21:00 UTC, bryce-mcmath commented on packages/legacy/core/App/localization/en/index.ts
> +      "PINTooLongValidation": "The PIN is long enough.",
Should this not say "is too long."?

2024-11-14 23:02 UTC, FarjadGov14 commented on packages/legacy/core/App/localization/en/index.ts
> +      "PINTooLongValidation": "The PIN is long enough.",
modified both

2024-11-15 20:36 UTC, FarjadGov14 commented on packages/legacy/core/App/localization/en/index.ts
> +      "PINTooLongValidation": "The PIN is long enough.",
@bryce-mcmath good to go

2024-11-15 20:42 UTC, bryce-mcmath approved these changes

2024-11-15 20:42 UTC, merged