Unify UI for Didcomm and OpenID flows for Offer and details screens
openwallet-foundation/bifold-wallet pull request #1365
Opened 2024-12-18 05:02 UTC by MosCD3

# Summary of Changes

Replace this text with a high-level summary of the changes included in this PR.

# Screenshots, videos, or gifs

Replace this text with embedded media for UI changes if they are included in this PR. If there are none, simply enter N/A

# Breaking change guide

Replace this text with any breaking changes included in this PR along with how to address them in downstream projects. If there are none, simply enter N/A

# Related Issues

Replace this text with issue #'s that are relevant to this PR. If there are none, simply enter N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this)
- [ ] If applicable, screenshots, gifs, or video are included for UI changes
- [ ] If applicable, breaking changes are described above along with how to address them
- [ ] Updated documentation as needed for changed code and new or modified features
- [ ] Added sufficient [tests](../packages/legacy/core/__tests__/) so that overall code coverage is not reduced

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated checks have passed

2024-12-19 21:33 UTC, jleach requested changes

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/components/views/CredentialDetailPrimaryHeader.tsx
> +type Props = {
Able to rename to `CredentialDetailPrimaryHeaderProps` to follow the app convetion?

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/components/views/CredentialDetailSecondaryHeader.tsx
> +type Props = {
`CredentialDetailSecondaryHeaderProps` to follow convention.

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialDetails.tsx
> +      if (!credentialDisplay || !bundleResolver || !i18n || !credentialDisplay.display) {
In the above two `useEffect` you put the guard clause `if (x) return` outside of the async function. Able to move this out or the other two in for consistency?

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialDetails.tsx
> +  const screenEdges: Edge[] = ['left', 'right']
This var seems orphaned down here. Can it be moved up with the others for readability?

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +      if (!credentialDisplay || !bundleResolver || !i18n || !credentialDisplay.display) {
outside for consistency?

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why "disable"?

2024-12-19 21:33 UTC, jleach commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +            {/* <OpenIDCredentialCard credentialDisplay={display} /> */}
Remove dead code?

2025-01-06 03:30 UTC, MosCD3 commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
For some reason, including 'credentialDisplay' in the dept array, causes infinite rendering loop. I spent enough time trying to dig deeper but couldn't figure out the reason. Removing this from the dept array makes rendering more stable.

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +            {/* <OpenIDCredentialCard credentialDisplay={display} /> */}
done

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialOffer.tsx
> +      if (!credentialDisplay || !bundleResolver || !i18n || !credentialDisplay.display) {
done

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialDetails.tsx
> +  const screenEdges: Edge[] = ['left', 'right']
done

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/modules/openid/screens/OpenIDCredentialDetails.tsx
> +      if (!credentialDisplay || !bundleResolver || !i18n || !credentialDisplay.display) {
done

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/components/views/CredentialDetailSecondaryHeader.tsx
> +type Props = {
done

2025-01-06 03:31 UTC, MosCD3 commented on packages/legacy/core/App/components/views/CredentialDetailPrimaryHeader.tsx
> +type Props = {
done

2025-01-09 18:43 UTC, jleach approved these changes

2025-01-09 18:53 UTC, jleach commented
Checked out and tested. LGTM.

2025-01-09 18:53 UTC, merged