chore: add accessibility props to components and screens
openwallet-foundation/bifold-wallet pull request #1370
Opened 2024-12-20 16:22 UTC by fc-santos

# Summary of Changes

This PR adds accessibility props to components/screens that were missing it.

# Screenshots, videos, or gifs

N/A

# Breaking change guide

N/A

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this)
- [x] If applicable, screenshots, gifs, or video are included for UI changes
- [x] If applicable, breaking changes are described above along with how to address them
- [x] Updated documentation as needed for changed code and new or modified features
- [x] Added sufficient [tests](../packages/legacy/core/__tests__/) so that overall code coverage is not reduced

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated checks have passed

2024-12-20 21:52 UTC, al-rosenthal commented on packages/legacy/core/App/screens/UseBiometry.tsx
> +            <Text accessible={false}></Text>
if these aren't rending text we should just remove them and add padding if we need the space

2024-12-24 20:59 UTC, bryce-mcmath requested changes
The vast majority of these changes are great, but I agree with Alfred that we should remove the empty `<Text>` tags

2025-01-03 00:57 UTC, bryce-mcmath approved these changes

2025-01-03 00:57 UTC, merged

2025-01-03 14:05 UTC, fc-santos commented
@bryce-mcmath Are you able to tell why my last two PR's that were merged into main failed on the release step ?

2025-01-03 19:17 UTC, bryce-mcmath commented
@fc-santos It is weird! I'm looking into it but so far I don't know what is causing it. All of the latest npm alpha versions are at 400 and the latest github tag is 400, but it's attempting to publish 402 instead of 401. That could have something to do with it but I'm pretty sure it's been able to skip a version in the past and still publish without issue.