chore: added indicio mainnet and demonet to ledgers
openwallet-foundation/bifold-wallet pull request #370
Opened 2022-07-13 19:37 UTC by seajensen

Signed-off-by: seajensen <seajensen@gmail.com>

# Summary of Changes

Added Indicio main net and demo net to ledgers

# Related Issues

https://indicio.atlassian.net/browse/AMO-405

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2022-07-19 23:05 UTC, jleach requested changes
Can be merged once the lint issues are fixed.

2022-08-08 20:34 UTC, jleach commented
@seajensen Able to pull in the changes from the base branch so we can get this change merged in. Ty.

2022-08-10 17:29 UTC, seajensen commented
> @seajensen Able to pull in the changes from the base branch so we can get this change merged in. Ty.

Should be fixed now

2022-08-11 15:15 UTC, jleach submitted a review, later dismissed

2022-09-13 15:28 UTC, JamesKEbert requested changes
LGTM besides a minor typo

2022-09-13 15:28 UTC, JamesKEbert commented on core/configs/ledgers/indy/indicio-main-net/genesis-file.ts
> +⚠{"reqSignature":{},"txn":{"data":{"data":{"alias":"IdRamp-Main","blskey":"4S14ydD6SJzfmBHBDJNKGmdzPDa5kh2mAQLmVGRCLXkQWyQErSfmS1aYDzYA25SAqg2cbfsQku1ZvwqXDRcsbEsdkNRHM66VhdceFv9B4aPQHBQsDkB2536bd5XK
Could you fix this typo @seajensen

2022-09-14 17:56 UTC, JamesKEbert approved these changes
👍

2022-09-14 17:56 UTC, merged