added multi logo support
openwallet-foundation/bifold-wallet pull request #379
Opened 2022-07-26 19:23 UTC by wadeking98

Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

# Summary of Changes

Added support for primary and secondary logo. Useful if you wish to display a light version of the logo for a dark background.

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2022-07-26 20:34 UTC, amanji requested changes

2022-07-26 20:34 UTC, amanji commented on core/App/components/animated/LoadingIndicator.tsx
> +      <Image source={Assets.img.logoSecondary.src} testID={testIdWithKey('LoadingActivityIndicatorX')} />
Nit: can we make this `logoPrimary` since it is used in more than one screen compared to `logoSecondary`?

2022-07-26 20:34 UTC, amanji commented on core/App/screens/PinEnter.tsx
> +            resizeMode: Assets.img.logoPrimary.resizeMode,
Please rename this to `logoSecodary` since it is different from the other main logos

2022-07-28 20:08 UTC, amanji approved these changes

2022-07-29 21:54 UTC, jleach commented
@wadeking98 Able to pull in the changes from the base branch so we can get this one merged in?

2022-07-29 21:59 UTC, merged