lock user out after 5 minutes of inactivity
openwallet-foundation/bifold-wallet pull request #456
Opened 2022-09-28 17:03 UTC by wadeking98

Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

# Summary of Changes

Log out the user and shutdown the agent if the app has been in the background (or the phone has been asleep) for 5 minutes
![image](https://user-images.githubusercontent.com/36937407/192844720-fbe896b5-ee95-49dc-88ad-c06c09ff17c9.png)

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2022-09-29 17:34 UTC, jleach requested changes
A few comments for consideration.

2022-09-29 17:34 UTC, jleach commented on core/App/contexts/auth.tsx
> +  wipeSavedWalletSecret: () => void
better terminology for "wipe" like remove, clear or delete. I get wipe but maybe harder for non-english spears.

2022-09-29 17:34 UTC, jleach commented on core/App/navigators/RootStack.tsx
> +      const MS_PER_MINUTE = 60000
Prefer cammelCaseForVars as its what we generally use throughout the app.

2022-09-29 17:34 UTC, jleach commented on core/App/screens/Splash.tsx
> +        let newAgent = agent
Does this do anything? I think objects are passed by ref so I'm not sure it will mint a new object.

2022-09-30 19:38 UTC, jleach requested changes

2022-09-30 19:38 UTC, jleach commented on core/App/navigators/RootStack.tsx
> +      const msPerMinute = 60000
Can you move this to `constants.ts` I think it's something that many deployments will want to customize.  Would be handy for `0` to mean dont-lock-ever-any-timeout.

2022-09-30 20:09 UTC, wadeking98 commented on core/App/navigators/RootStack.tsx
> +      const msPerMinute = 60000
done

2022-09-30 20:21 UTC, jleach approved these changes

2022-09-30 20:21 UTC, merged