Feat: oca dateint formatage
openwallet-foundation/bifold-wallet pull request #505
Opened 2022-10-25 17:49 UTC by jcdrouin21

# Summary of Changes

This PR use OCA format overlay to display date in the wanted format.

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2022-10-25 22:25 UTC, cvarjao commented
@jcdrouin21 , can you add any unit testing including this type/format?

2022-10-25 22:28 UTC, jleach commented on core/App/components/record/RecordDateIntField.tsx
> +    if (dayjs((field as Attribute).value as string, dateIntFormat, true).isValid()) {
Can we do this without adding more JS modules? For example:
```
today = new Date();
today.format('dd-m-yy'); // Returns '02-8-16'
```

2022-10-25 22:32 UTC, jleach requested changes

2022-10-25 22:32 UTC, jleach commented on core/App/components/record/RecordDateIntField.tsx
> +const dateIntFormat = 'YYYYMMDD'
Should this go in constants so that it can be changed in once place and impact the entire app wherever the format is used.

2022-10-25 22:32 UTC, jleach commented on core/App/components/record/RecordDateIntField.tsx
> +      {shown ? date : Array(10).fill('\u2022').join('')}
10 seems like a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)). Can we do `const paddingBetweenFields = 10` or something like that?

2022-11-09 23:10 UTC, jleach approved these changes

2022-11-10 13:40 UTC, jleach approved these changes

2022-11-10 13:40 UTC, merged