feat: added exact time to issued date
openwallet-foundation/bifold-wallet pull request #576
Opened 2022-12-20 23:44 UTC by wadeking98

Signed-off-by: wadeking98 <wkingnumber2@gmail.com>

# Summary of Changes

Added exact time to issued attribute in credential details screen, this allows the user to know which credential is newest between multiple credentials issued on the same day.

![image](https://user-images.githubusercontent.com/36937407/208787332-42f20112-fedf-45c8-a956-682be5822ac5.png)

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2022-12-21 00:48 UTC, jleach requested changes
The format used elsewhere in the app is:

`aDate.toLocaleDateString('en-CA', dateFormatOptions)}` where `dateFormatOptions` comes from constants. If you search for `toLocaleDateString` you'll fine examples. Fine to hard code `en-CA` for now but I think this needs to come from the current language of the phone. That way its in a ISO 8601 format and will show properly in French (et al):

```
> n.toLocaleDateString('fr-CA', { day: 'numeric', month: 'long',  year: 'numeric'})
'20 décembre 2022'
```

Also, consider extracting it to a fn that just returns the date with time. Not required though. Just an idea.

2022-12-21 02:13 UTC, amanji commented
I'd also consider getting the locale directly from `i18n` rather than passing hardcoded locales. I don't think we need to further abstract into another function since we're calling a method directly on the date object itself. But definitely make use of the `dateTimeFormat` in constants.

2022-12-21 17:12 UTC, wadeking98 commented
right, the issue I'm running into with i18n is that it doesn't use the full locale string, just `fr` instead of `fr-CA`

2022-12-21 19:51 UTC, wadeking98 commented
@amanji and @jleach, I'm running into issues with the locale date string in react native:
## javascript:
- input: `(new Date()).toLocaleDateString('fr', { day: 'numeric', month: 'long',  year: 'numeric'})`
- output: `21 décembre 2022`  
  
## react-native:
- input: `(new Date()).toLocaleDateString('fr', { day: 'numeric', month: 'long',  year: 'numeric'})`
- output: `December 21, 2022`  
  
I've tried with different locales too but it seems like react-native doesn't support locales on dates: https://stackoverflow.com/questions/51399551/why-isnt-tolocaledatestring-working-in-react-native-android

Judging by the comments it seems like it behaves differently on IOS than Android

2022-12-21 23:33 UTC, wadeking98 commented
Just tested with moment, still running into the same issue. It seems like the issue must be in the core of react-native

2023-01-04 22:00 UTC, jleach commented
@wadeking98 Interesting. Must be a lack of compatibility in the [Hermes](https://reactnative.dev/docs/hermes) JS engine. I suppose that is what it is. We can leave it for now and see if it improves in RH 0.70.0 if not use a 3rd party library like moment.js or perhaps a polly-fill.

2023-01-05 23:46 UTC, amanji reviewed
I'm not sure if I agree with having this be a standalone implementation for date time formatting. While I get the need for localization I think we should look at being consistent with date representation.

2023-01-05 23:48 UTC, amanji commented
I would go so far to say that we create a helper function that outputs the right format and update every method call to `.toLocaleDateString` for consistency.

2023-01-05 23:50 UTC, amanji requested changes
Please see my comments in the PR

2023-01-12 17:49 UTC, wadeking98 commented
> I would go so far to say that we create a helper function that outputs the right format and update every method call to `.toLocaleDateString` for consistency.

@amanji should we just use something like moment then?

2023-01-12 18:10 UTC, amanji commented
I think so

2023-01-19 21:52 UTC, closed without merging