feat: added connection image to proof & cred offer
openwallet-foundation/bifold-wallet pull request #648
Opened 2023-03-01 23:38 UTC by wadeking98

# Summary of Changes

Added connection Image URL to proof request and credential offer page:

Note, I will need to change some of the images in the bc wallet demo since they're still pointing to some animo images
![Screen Shot 2023-03-01 at 3 33 58 PM](https://user-images.githubusercontent.com/36937407/222291327-45ba059a-897e-4baa-beaf-c46b11cf8c06.png)
![Screen Shot 2023-03-01 at 3 34 31 PM](https://user-images.githubusercontent.com/36937407/222291369-77d4fb88-ad9a-4ad9-a178-f0c9250d2bbf.png)

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [ ] Updated documentation as needed for changed code and new or modified features;
- [ ] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2023-03-03 00:02 UTC, jleach requested changes

2023-03-03 00:02 UTC, jleach commented on core/App/screens/ProofRequest.tsx
> +  const connectionImage = getConnectionImageUrl(proof?.connectionId)
In the previous file you used `??` to coalesce this to and empty string but not here. I think using one or the other is better.

2023-03-03 00:02 UTC, jleach commented on core/App/utils/helpers.ts
> +export function getConnectionImageUrl(connectionId: string) {
I think this fn can return an actual url, and empty string, or undefined. Might be better to just return a non-empty string or undefined to better K.I.S.S.

2023-03-03 20:40 UTC, amanji commented on core/App/screens/ProofRequest.tsx
> +                <View style={styles.connectionImageContainer}>
Can this just be a component in misc since were reusing styles in both places?

2023-03-03 23:21 UTC, amanji approved these changes

2023-03-06 17:11 UTC, amanji approved these changes

2023-03-06 17:13 UTC, jleach approved these changes

2023-03-06 17:13 UTC, merged