feat: in app tour
openwallet-foundation/bifold-wallet pull request #722
Opened 2023-04-21 06:30 UTC by bryce-mcmath

# Summary of Changes

Implementing our first in-app tour. The feature is optional and is not configured to be on by default. Here's what it looks like:
![in_app_tour](https://user-images.githubusercontent.com/32586431/233558045-7fe638c6-84d5-4533-9694-730227cccc94.gif)
Apologies for the many changes, it was a painful feature to implement.

# Related Issues

N/A

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2023-04-21 19:01 UTC, jleach requested changes
A few comments for consideration. Will checkout and test short.

2023-04-21 19:01 UTC, jleach commented on packages/legacy/core/App/components/modals/AppGuideModal.tsx
> +      <TouchableOpacity onPress={onDismissPressed} accessible={false}>
Does this need `testID` or `accessabilityID` or are the child buttons good enough?

2023-04-21 19:01 UTC, jleach commented on packages/legacy/core/App/components/tour/TourBox.tsx
> +  const { leftText = 'Back', rightText = 'Next', title, hideLeft, hideRight, onLeft, onRight, children, stop } = props
Translations for Back and Next?

2023-04-21 19:01 UTC, jleach commented on packages/legacy/core/App/components/tour/TourOverlay.tsx
> +    <Modal animationType="fade" presentationStyle="overFullScreen" transparent={true} visible={current !== undefined}>
Is `foo === undefined` ok in TS? I forget if its ok or we need `typeof foo !== 'undefined'`?

2023-04-21 19:01 UTC, jleach commented on packages/legacy/core/App/screens/Tours.tsx
> +const Tours = () => {
Bit of a different signature than we normally use: `const x = React.FC<XX> ...`.

2023-04-21 19:01 UTC, jleach commented on packages/legacy/core/App/contexts/tour/tour-context.tsx
> +export const ZERO_SPOT: LayoutRectangle = {
Origin maybe?

2023-04-21 21:55 UTC, wadeking98 commented on packages/legacy/core/App/components/tour/TourOverlay.tsx
> +    <Modal animationType="fade" presentationStyle="overFullScreen" transparent={true} visible={current !== undefined}>
I think `foo === undefined` works fine

2023-04-21 22:36 UTC, wadeking98 approved these changes, later dismissed
once's jason's changes are addressed it looks good to me

2023-04-24 17:18 UTC, jleach approved these changes

2023-04-24 17:18 UTC, merged