Feature/proof request
openwallet-foundation/bifold-wallet pull request #75
Opened 2021-08-23 20:28 UTC by NeilSMyers

# Summary of Changes

Replace this text with a high-level summary of the changes included in this PR.

# Related Issues

Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.

# Pull Request Checklist

This is just a reminder about the most common mistakes. Please make sure that you tick all _appropriate_ boxes. But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [ ] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [ ] Run prettier: `npm run style-format`
- [ ] Updated **documentation** for changed code and new or modified features.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

_PR template adapted from the Python attrs project._

2021-08-24 07:27 UTC, TimoGlastra approved these changes, later dismissed
Nice! A lot to review in a single PR, but I like that we're updating to latest AFJ version. 

I'd be interested to see a demo of this new functionality at the WG call!

2021-08-25 17:14 UTC, JamesKEbert requested changes
Looks great! A couple of minor tweaks requested--and can be resolved with the merge conflicts.

2021-08-25 17:14 UTC, JamesKEbert commented on App/screens/CredentialDetails.tsx
> +      <Label title="Age" subtitle={age} />
This is something that we will need to fix in the future--this needs to be generic and not tied to a specific set of attributes, but I'd rather merge and do a followup PR.

2021-08-25 17:14 UTC, JamesKEbert commented on App/screens/EntryPoint.tsx
> +import LoadingOverlay from '../components/modals/LoadingOverlay'
I think we _might_ not need this component?

2021-08-25 17:14 UTC, JamesKEbert commented on App/screens/Home.tsx
> +  console.log('PROOFS', proofs)
Unneeded console log?

2021-08-25 17:14 UTC, JamesKEbert commented on App/screens/ProofRequest.tsx
> +      credentialDefinitionId: attributes[attribute][0].credentialInfo.credentialDefinitionId
Would prefer to take the schema name for this to mimic the credential offer/issuance.

2021-08-25 17:14 UTC, JamesKEbert commented on App/screens/ProofRequest.tsx
> +      credentialDefinitionId: attributes[attribute][0].credentialInfo.credentialDefinitionId
And this can use the parseSchema function too

2021-08-25 17:14 UTC, JamesKEbert commented on aries-hooks/package.json
> +  "license": "ISC",
We need to make sure this "Apache-2.0" for the license.

2021-08-25 17:18 UTC, manghuli commented on App/screens/CredentialDetails.tsx
> +      <Label title="Age" subtitle={age} />
ya, we still aren't using this component at all, it's just a placeholder for now

2021-08-25 17:20 UTC, JamesKEbert commented on App/screens/CredentialDetails.tsx
> +      <Label title="Age" subtitle={age} />
Ahh I see 👍

2021-08-25 17:21 UTC, manghuli commented on App/screens/ProofRequest.tsx
> +      credentialDefinitionId: attributes[attribute][0].credentialInfo.credentialDefinitionId
i went through and couldn't find a schemaId on that object anywhere, but I'll check again

2021-08-25 18:54 UTC, manghuli commented on App/screens/EntryPoint.tsx
> +import LoadingOverlay from '../components/modals/LoadingOverlay'
removed

2021-08-25 18:54 UTC, manghuli commented on App/screens/Home.tsx
> +  console.log('PROOFS', proofs)
removed

2021-08-25 21:50 UTC, manghuli commented on App/screens/ProofRequest.tsx
> +      credentialDefinitionId: attributes[attribute][0].credentialInfo.credentialDefinitionId
oof, it was right there the whole time haha my bad

2021-09-08 16:24 UTC, JamesKEbert commented
Would you be able to resolve the merge conflicts here @NeilSMyers?

2021-09-08 16:57 UTC, JamesKEbert approved these changes
Looks great! Appreciate your work here!

2021-09-08 16:58 UTC, merged