fix: ios require full screen
openwallet-foundation/bifold-wallet pull request #910
Opened 2023-08-04 20:49 UTC by jleach

# Summary of Changes

Better adapted the application to work in landscape orientation for both iOS and Android.

- Better fetch screen dimetions
- Allow iOS tablets to rotate but not iPhones. 

# Related Issues

n/a

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2023-08-05 00:04 UTC, bryce-mcmath requested changes

2023-08-05 00:04 UTC, bryce-mcmath commented on packages/legacy/core/App/screens/ProofRequesting.tsx
> +const calculateQrSizeForDevice = () => {
Should this be `useQrSizeForDevice` since it's a hook?

2023-08-05 00:04 UTC, bryce-mcmath commented on packages/legacy/core/__tests__/screens/__snapshots__/Home.test.tsx.snap
> +              "width": NaN,
This seems concerning

2023-08-23 00:00 UTC, jleach commented on packages/legacy/core/App/screens/ProofRequesting.tsx
> +const calculateQrSizeForDevice = () => {
Fixed

2023-08-23 00:05 UTC, jleach commented on packages/legacy/core/__tests__/screens/__snapshots__/Home.test.tsx.snap
> +              "width": NaN,
Fixed

2023-08-23 00:10 UTC, bryce-mcmath approved these changes

2023-08-23 00:24 UTC, merged