Add workflow to build for iOS and Android
openwallet-foundation/bifold-wallet pull request #93
Opened 2021-10-20 17:46 UTC by jleach

# Summary of Changes

Added a GitHub Actions based wrokflow to make sure the application combines for both iOS and Android.

# Related Issues

I thought we could address #92 with two PRs. The first hist to beef up the workflows by demonstrating that the project can compile for both iOS and Android. This will help ensure no breaking changes are included by contributors. The down side, is that it takes about 25 mins for the iOS build to run on GitHub hardware. Not an overly big issue since its all background work.

The second pull request would be to fix all the LINT issues and then add `npm run lint` back into this workflow or another just for listing. It may also be worth adding husky support to run a lint check on commit to not allow un-formatted code to be pushed out in the first place.

**NOTE**: This will burn through allot of build minutes for private repositories. Build minutes on `macOS` are billed at 10x so a 25 min run-time will be 250 minutes. 

# Pull Request Checklist

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [X] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [X] Run prettier: `npm run style-format`
- [X] Updated **documentation** for changed code and new or modified features.

2021-10-20 17:49 UTC, jleach commented
@JamesKEbert Your thoughts on adding this to the main repo. Because RN depends on 3rd-party components integrated directly into the iOS and Android projects that require linking or `pod install` it would be good to make sure that no contributions break-the-build. The down side, as noted above it takes some time for the iOS build to run on GitHub provided hardware. The up side is that it is free and a background task. Could be moved to run on merges to master only but by that times breaking changes are harder to unwind.

2021-10-20 20:14 UTC, TimoGlastra commented
I like it! Would be good to eventually add Detox testing to make sure the basic flow of creating connections, receiving credentials and sharing proofs is still working as expected.

Do you think caching could help with the iOS build times. Incremental builds are way faster than cold builds

2021-10-20 20:18 UTC, jleach commented
@TimoGlastra I've put in as much caching as I can. Caching build artifacts seems like it would help (Android only takes 5min) but I haven't figured out how to do it (despite some effort). I can take one last try but if I can't speed it up I think there is still value in a binary compile.

2021-10-21 17:29 UTC, JamesKEbert commented
@jleach I would fully be in favor of adding this to the main repo! 

> It may also be worth adding husky support to run a lint check on commit to not allow un-formatted code to be pushed out in the first place.

We should be using Husky right now IIRC for ensuring DCO signoff, so it wouldn't be that hard to add a linting check too.

2021-10-21 23:14 UTC, jleach commented
No progress on the build time for iOS. It's not using the cache for some reason. I think it may be `npm ci` or `pod install` causing the intermediate build artifacts to expire. I've updated the path triggers to only run the native build when something meaningful changes. I don't think it needs to run when a `*.tsx,*.ts` file change as that would trigger a run-time error. Only changes to `ios/**`, `android/**` or `package-lock.json` will trigger this workflow.

2021-10-21 23:18 UTC, jleach commented
Added this note to my original description above:
```
NOTE: This will burn through allot of build minutes for private repositories. Build
minutes on macOS are billed at 10x so a 25 min run-time will be 250 minutes.
```

2021-10-22 06:56 UTC, TimoGlastra requested changes
This is great @jleach!

Only the comment should be fixed I think, but for the rest good to go

2021-10-22 06:56 UTC, TimoGlastra commented on .github/workflows/continuous-integration.yml
> +  #   branches: [main]
I'd like to keep running this on PRs and pushes to main

2021-10-22 06:56 UTC, TimoGlastra commented on .github/workflows/main.yaml
> +      - '**/package-lock.json'
To not run it on every branch and push I normally do it on pull_request and push to main. This way it will always run before a PR is merged (and we can set the job to required for the PR to be mergeable)

```
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
```

2021-10-22 14:52 UTC, jleach commented on .github/workflows/continuous-integration.yml
> +  #   branches: [main]
I agree. I disabled it for now until all the LINT issues are resolved. I'm going to clean them up and re-enable this workflow as part of a new PR I'll start on today.

2021-10-22 14:54 UTC, jleach commented on .github/workflows/main.yaml
> +      - '**/package-lock.json'
Are you thinking something like this? There may be some value removing `paths:` from pushes to main just to be sure `main` always compiles.

```
on:
  pull_request:
    branches: [main]
    paths:
      - 'ios/**'
      - 'android/**'
      - '**/package-lock.json'
  push:
    branches: [main]
    paths:
      - 'ios/**'
      - 'android/**'
      - '**/package-lock.json'
 ```

2021-10-25 17:36 UTC, TimoGlastra commented on .github/workflows/main.yaml
> +      - '**/package-lock.json'
Sorry forgot to comment on your reply. But yes, that what what I was thinking about. I think you suggestion to remove paths for pushes to main makes sense

2021-10-25 17:38 UTC, TimoGlastra submitted a review, later dismissed
This is great @jleach!

2021-10-25 17:38 UTC, TimoGlastra commented on .github/workflows/main.yaml
> +  cacheId: '3' # increment to expire the cache
Is there a specific reason this is needed?

2021-10-25 18:45 UTC, jleach commented on .github/workflows/main.yaml
> +  cacheId: '3' # increment to expire the cache
@TimoGlastra I've had one situation (on this project) where the npm cache `~/.npm` was borked causing issues. Caches cannot be deleted in GitHub. The only way to fix it is to create a new cache and let the old one expire naturally. This takes care of that. Bump the number and a fresh set of caches are created.

2021-10-25 19:00 UTC, jleach commented on .github/workflows/main.yaml
> +      - '**/package-lock.json'
@TimoGlastra Done. Main will always build:

```yaml
on:
  pull_request:
    branches: [main]
    paths:
      - 'ios/**'
      - 'android/**'
      - '**/package-lock.json'
  push:
    branches: [main]
```

2021-10-25 23:47 UTC, JamesKEbert approved these changes
Looks great to me! Good work @jleach

2021-10-26 14:17 UTC, merged