feat: disable 'Change PIN' button if a PIN input is empty
openwallet-foundation/bifold-wallet pull request #966
Opened 2023-09-12 18:54 UTC by SophiaSales

# Summary of Changes
![Captura de tela de 2023-09-12 14-46-46](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/69023582/2880a3ce-c109-4a5b-a750-bf79da01e3da) ![Captura de tela de 2023-09-12 14-45-47](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/69023582/623ad5be-64ec-4b6f-ad33-840bbe00a5d8)

If any of the PIN inputs (current, new and confirm new) are empty, the 'Change PIN' button should be disabled.

# Related Issues

N/A.

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [X] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [X] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [X] Updated documentation as needed for changed code and new or modified features;
- [X] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

2023-09-22 18:41 UTC, bryce-mcmath requested changes

2023-09-22 18:41 UTC, bryce-mcmath commented on packages/legacy/core/App/screens/PINCreate.tsx
> +    return p !== '' && PIN !== '' && PINTwo !== ''
Just noticing there is no check for PINOld here

2023-09-22 18:41 UTC, bryce-mcmath commented on packages/legacy/core/App/screens/PINCreate.tsx
> +              setContinueEnabled(checkEmptyPINs(p))
Should this `p` be disregarded and just include a check in `checkEmptyPINs` for `PINOld`?

2023-09-22 18:41 UTC, bryce-mcmath commented on packages/legacy/core/App/screens/PINCreate.tsx
> +              setContinueEnabled(checkEmptyPINs(p))
Same as above

2023-09-22 18:41 UTC, bryce-mcmath commented on packages/legacy/core/App/screens/PINCreate.tsx
> +                setContinueEnabled(checkEmptyPINs(p))
Same as below

2023-09-25 11:20 UTC, thiagoromanos commented
Suggestion for this PR: you could use a `useEffect` function watching `[PINOld, PIN, PINTwo]` that validate those values if `updatePin == true`, instead of whatching every input change.
What do you think, @SophiaSales and @bryce-mcmath ?

2023-09-25 22:31 UTC, bryce-mcmath commented
> Suggestion for this PR: you could use a `useEffect` function watching `[PINOld, PIN, PINTwo]` that validates those values if `updatePin == true`, instead of watching every input change. What do you think, @SophiaSales and @bryce-mcmath ?

That works for me!

2023-09-26 16:52 UTC, bryce-mcmath approved these changes

2023-09-26 17:06 UTC, SophiaSales commented
@bryce-mcmath, I have no write permission. Can you merge this PR for me?

2023-09-26 18:01 UTC, merged

2023-09-26 18:01 UTC, bryce-mcmath commented
> @bryce-mcmath, I have no write permission. Can you merge this PR for me?

Done! Nice work.